### ISSUE TITLE
demo error

### ISSUE THREAD

**Issue by llpspark** [qianlim/SCALE#13]
great work for human modeling. and when I run the demo, the error appear at chamferdist：
    
<img width="706" alt="屏幕快照 2022-04-13 下午11 24 08" src="https://user-images.githubusercontent.com/20918669/163215475-899acc19-f7cf-4684-b269-0bbbe4375e0e.png">
what's wrong with that?

**Comment by qianlim** [comment]
Could you print the shape of the `output` and `target` ?

**Comment by llpspark** [comment]
> Could you print the shape of the `output` and `target` ?

<img width="912" alt="屏幕快照 2022-04-14 上午11 28 54" src="https://user-images.githubusercontent.com/20918669/163308159-97e61816-8172-4cde-af9b-b65c94417822.png">
I found the 0th dim is same but 1th dim different between output and target, and I think it maybe rational.

**Comment by llpspark** [comment]
it have solved. case by my wrong chamferdist package's installation, thank you again.
