### ISSUE TITLE
posmap error

### ISSUE THREAD

**Issue by 1815565** [qianlim/SCALE#17]
Excellent work!  But why when I run the command" python lib_data/pack_data_example.py", it will appear the error"'Compilation failure for fragment shader:b"0:7(1): error: if a fragment input is (or contains) an integer, then it must be qualified with 'flat'\n0:7(8): error: `gl_PrimitiveID' redeclared"'?

**Comment by qianlim** [comment]
Hi, this sounds like an OpenGL error which I can't reproduce. On which platform are you using the code?

**Comment by 1815565** [comment]
Thanks for your quick reply. I use the Ubuntu20.04，and the version of pyopengl is 3.1.0.

**Comment by 1815565** [comment]
@qianlim , Maybe you not provide the "pos_uv.fs" and the "pos_uv.vs"?

**Comment by 1815565** [comment]
oh~ I solve the problem, it need to modify some information in "pos_uv.fs" and "pos_uv.vs" to adapt to my environment.

**Comment by 1815565** [comment]
oh~, I just solve the problem by deleting the "in int gl_PrimitiveID;" in "pos_uv.fs".

**Comment by qianlim** [comment]
Oh sorry for my late response. Great to hear that it's resolved!
