### ISSUE TITLE
question: how to get a fitted, unclothed SMPL body mesh for a custom clothed mesh for training

### ISSUE THREAD

**Issue by codesavory** [qianlim/SCALE#3]
The project assumes we have a fitted, unclothed SMPL body mesh for each custom clothed mesh. Do you have tools which can fit a SMPL body mesh to the given custom clothed mesh or do you have any suggested method to achieve the same. Thank you for the amazing work.

**Comment by qianlim** [comment]
Hi, we use some internal body fitting tools, but here are several recent papers (all with code) that addresses your needs: [IP-Net](https://virtualhumans.mpi-inf.mpg.de/ipnet/), [LoopReg](https://virtualhumans.mpi-inf.mpg.de/loopreg/), [PTF](https://github.com/taconite/PTF).

**Comment by codesavory** [comment]
Thank you for pointing to these amazing resources!
