### ISSUE TITLE
question

### ISSUE THREAD

**Issue by HDYYZDN** [qianlim/SCALE#7]
我在render 渲染的时候出现了GLFW Error: GLX: Failed to create context: GLXBadFBConfig，Failed to create window
 ，这个如何解决，open3d==0.13.0

**Comment by qianlim** [comment]
I can't reproduce this on my machine. Also without knowing your machine's configurations it'd be hard to debug. Have you searched for solution on the internet?

**Comment by HDYYZDN** [comment]
ubuntu 18.04.4  cuda 11.2

**Comment by HDYYZDN** [comment]
而且还会显示 AttributeError: 'NoneType' object has no attribute 'point_size'
