### ISSUE TITLE
论文

### ISSUE THREAD

**Issue by HDYYZDN** [qianlim/SCALE#8]
想请问一下，你的论文实验使用了cape 数据集，blazerlong1334 / 563;shortlong  3480 / 976，但是cape 03375中blazerlong数据量大于1334，想文一下，你是否使用了数据筛选？

**Comment by qianlim** [comment]
Yes we randomly split the data into train/val/test splits. Those not in the train/test are in either in val set of discarded du to the high temporal sampling density. In the CAPE dataset website, bottom of the download page, we now provide the original packed data that we used in the SCALE paper. There, the 03375_blazerlong has exactly 1334+563 frames.
